# For more information on how to use SAYN, please visit our documentation:
# https://173tech.github.io/sayn/


#PROJECT OVERVIEW

# Details of the SAYN project - this file is shared across all project users
# For more information about the "project.yaml", please see the specific documentation:
# https://173tech.github.io/sayn/settings/project_yaml/


#REQUIRED CREDENTIALS SECTION

# Specifies the list of the required credentials to run the project
# Note: The details of those credentials are specified into "settings.yaml"
required_credentials:
  - warehouse


#DEFAULT DATABASE SECTION

# Specifies the default database when running SAYN
# Note: Specified database need to be part of the required_credentials
default_db: warehouse


# Presets used in the project
# This project uses one preset for the AutoSQL tasks
presets:
  modelling:
    type: autosql
    materialisation: table
    file_name: "{{ task.name }}.sql"
    destination:
      table: "{{ user_prefix }}{{ task.name }}" # Dynamic table names


# Parameters used in the project
# Note: These can be overwritten using settings.yaml or within individual tasks
parameters:
  user_prefix: # Change to your preferred prefix
