tasks:

  # Python

  # Performs NLP on dim_bbc_feeds
  nlp:
    type: python
    class: nlp.LanguageProcessing
    parents:
      - dim_reddit_feeds
    parameters:
      table: dim_reddit_feeds

  # Generates wordclouds for every link in load_data
  # The stopwords parameter adds additional stopwords to our task
  wordcloud:
    type: python
    class: wordcloud.RenderCloud
    parents:
      - dim_reddit_feeds
    parameters:
      table: dim_reddit_feeds
      stopwords:
        - Reddit
