tasks:

  # Python

  # Performs NLP on clean_data
  nlp:
    type: python
    class: nlp.LanguageProcessing
    parents:
      - f_bbc_feeds
    parameters:
      table: f_bbc_feeds
      text:
        - title
        - summary

  # Generates wordclouds for every link in load_data
  # The stopwords parameter adds additional stopwords to our task
  wordcloud:
    type: python
    class: wordcloud.RenderCloud
    parents:
      - f_bbc_feeds
    parameters:
      table: f_bbc_feeds
      stopwords:
        - say
        - said
        - says
        - will
        - country
        - US
        - England
        - Scotland
        - Wales
        - NI
        - Ireland
        - Europe
        - BBC
        - yn
