tasks:

  # Python

  # Use this to extract data from links and write to database
  load_data:
    type: python
    class: load_data.LoadData
    parameters:
      table: logs_reddit_feeds
      links:
        - https://www.reddit.com/r/USnews/new/.rss
        - https://www.reddit.com/r/UKnews/new/.rss
        - https://www.reddit.com/r/EUnews/new/.rss
