# This tutorial is composed of one DAG
# Please see the DAG section of the documentation for more details:
# https://173tech.github.io/sayn/dags/

# DAGs define at minimum a set of tasks
# Those will be run for this DAG when SAYN runs
# To run the tutorial, run the command 'sayn run' from the project folder's root
tasks:
  # python
  # here we define a Python task
  # python tasks are stored into the python folder

  load_data:
    type: python
    class: load_data.LoadData
    parameters:
      table: full_data
      links:
        - http://feeds.bbci.co.uk/news/england/rss.xml
        - http://feeds.bbci.co.uk/news/wales/rss.xml
        - http://feeds.bbci.co.uk/news/scotland/rss.xml
        - http://feeds.bbci.co.uk/news/northern_ireland/rss.xml
        - http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml
        - http://feeds.bbci.co.uk/news/world/middle_east/rss.xml
        - http://feeds.bbci.co.uk/news/world/latin_america/rss.xml
        - http://feeds.bbci.co.uk/news/world/europe/rss.xml
        - http://feeds.bbci.co.uk/news/world/asia/rss.xml
        - http://feeds.bbci.co.uk/news/world/africa/rss.xml


  nlp:
    type: python
    class: nlp.NLP
    parents:
      - clean_data
    parameters:
      table: clean_data
      text:
        - title
        - summary


  wordcloud:
    type: python
    class: wordcloud.RenderCloud
    parents:
      - clean_data
    parameters:
      table: clean_data
      stopwords:
        - say
        - said
        - says
        - will
        - country
        - US
        - England
        - Scotland
        - Wales
        - NI
        - Ireland
        - Europe
        - BBC
        - yn


  # autosql
  # autosql tasks enable to write a SELECT statement and SAYN creates the table / view automatically
  # the SQL queries for those models are stored into the sql folder

  clean_data:
    preset: modelling
    file_name: remove_duplicates.sql
    parents:
      - load_data
    parameters:
      table: full_data


  text_stats:
    preset: modelling
    file_name: group_summary.sql
    materialisation: view
    parents:
      - nlp
    parameters:
      table: clean_data_nlp
